const projects = [
  {
    id: "01",
    title: "Bid Taxi",
    websitelink: "https:/bidtaxi.az/",
    itemRoute: "bidTaxi",
    languages: ["React", "CSS", "HTML"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: [
      {
        id: 1,
        goalName: "Saving time",
        goalDesc:
          "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem perferendis tempora beatae facilis veniam aliquam enim necessitatibus optio non vel?",
      },
      {
        id: 2,
        goalName: "nese nese",
        goalDesc:
          "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem perferendis tempora beatae facilis veniam aliquam enim necessitatibus optio non vel?",
      },
      {
        id: 3,
        goalName: "lalalala",
        goalDesc:
          "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem perferendis tempora beatae facilis veniam aliquam enim necessitatibus optio non vel?",
      },
    ],
    challanges: "",
    solution: "",
    screenshots: "/assets/images/bid.png",
  },
  {
    id: "02",
    title: "E-SAYAR",
    websitelink: "https://www.e-sayar.az/",
    itemRoute: "esayar",

    languages: ["React", "SCSS", "HTML"],
    desc: "E-SAYAR is an accounting software platform that helps users to manage their accounting and audit operations easily and professionally using advanced and high-performance algorithms.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/esayar.png",
  },
  {
    id: "03",
    title: "Portfolio Website",
    websitelink: "https://fatimakarimli.netlify.app/",
    itemRoute: "bidTaxi",

    languages: ["React", "SCSS", "HTML"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/fatima.png",
  },
  {
    id: "04",
    title: "Eazy Pizz",
    websitelink: "https://eazypizz.netlify.app/home",
    itemRoute: "bidTaxi",

    languages: ["React", "Redux", "SCSS", "HTML"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/eazypizz.png",
  },
  {
    id: "05",
    title: "Naringi",
    websitelink: "http://naringi.az/",
    itemRoute: "bidTaxi",

    languages: ["React", "Redux", "SCSS", "HTML"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/naringi.png",
  },
  {
    id: "06",
    title: "Natours",
    websitelink: "https://natours-go.netlify.app/",
    itemRoute: "bidTaxi",

    languages: ["React", "SCSS", "HTML"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/natours.png",
  },
  {
    id: "07",
    title: "Nexter",
    websitelink: "https://nexter-go.netlify.app/",
    itemRoute: "bidTaxi",

    languages: ["React", "SCSS", "HTML"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/nexter.png",
  },
  {
    id: "08",
    title: "Trillo",
    websitelink: "https://trillo-go.netlify.app/",
    itemRoute: "bidTaxi",

    languages: ["React", "SCSS", "HTML"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/trillo.png",
  },

  {
    id: "09",
    title: "Selnet",
    websitelink: "https://selnet.az/",
    itemRoute: "bidTaxi",

    languages: ["HTML", "CSS", "Javascript"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/selnet.png",
  },
  {
    id: "10",
    title: "Portfolio Website",
    websitelink: "https://javid-hussain.netlify.app/",
    itemRoute: "bidTaxi",

    languages: ["React", "SCSS", "HTML"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/javid.png",
  },
  {
    id: "11",
    title: "Studio Ghibli",
    websitelink: "https://studio-ghibli-go.netlify.app/",
    itemRoute: "bidTaxi",

    languages: ["React", "SCSS", "HTML", "Redux"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/ghibli.png",
  },

  {
    id: "12",
    title: "Freud",
    websitelink: "https://sigmundfreud.netlify.app/",
    itemRoute: "bidTaxi",

    languages: ["React", "SCSS", "HTML", "GSAP"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/freud.png",
  },
  {
    id: "13",
    title: "Stremio",
    websitelink: "eazypizz.netlify.app",
    itemRoute: "stremio",

    languages: ["React", "SASS/SCSS", "HTML", "Redux"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "",
  },

  {
    id: "14",
    title: "Youtube App",
    websitelink: "https://youtube-go.netlify.app/g",
    itemRoute: "bidTaxi",
    languages: ["React", "SASS/SCSS", "HTML"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "",
  },
  {
    id: "15",
    title: "Currency Converter",
    websitelink: "https://youtube-go.netlify.app/g",
    itemRoute: "bidTaxi",

    languages: ["React", "SASS/SCSS", "HTML"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum placeat, expedita laboriosam eveniet amet, assumenda nesciunt laborum cumque ratione quo ullam numquam tenetur fugiat. Quos.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "",
  },
];
export default projects;
