const projects = [
  {
    id: "01",
    title: "Bid Taxi",
    websitelink: "https://bidtaxi.az/",
    languages: ["React", "CSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/bid.png",
  },
  {
    id: "02",
    title: "E-SAYAR",
    websitelink: "https://www.e-sayar.az/",
    languages: ["React", "SCSS", "HTML"],
    desc: "E-SAYAR is an accounting software platform that helps users to manage their accounting and audit operations easily and professionally using advanced and high-performance algorithms.",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/esayar.png",
  },
  {
    id: "03",
    title: "Portfolio Website",
    websitelink: "https://fatimakarimli.netlify.app/",
    languages: ["React", "SASS/SCSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/fatima.png",
  },
  {
    id: "04",
    title: "Eazy Pizz",
    websitelink: "https://eazypizz.netlify.app/home",
    languages: ["React", "Redux", "SCSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/eazypizz.png",
  },
  {
    id: "05",
    title: "Naringi",
    websitelink: "http://naringi.az/",
    languages: ["React", "Redux", "SCSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/naringi.png",
  },
  {
    id: "06",
    title: "Natours",
    websitelink: "https://natours-go.netlify.app/",
    languages: ["React", "SCSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/natours.png",
  },
  {
    id: "07",
    title: "Nexter",
    websitelink: "https://nexter-go.netlify.app/",
    languages: ["React", "SCSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/nexter.png",
  },
  {
    id: "08",
    title: "Trillo",
    websitelink: "https://trillo-go.netlify.app/",
    languages: ["React", "SCSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/trillo.png",
  },

  {
    id: "09",
    title: "Selnet",
    websitelink: "https://selnet.az/",
    languages: ["HTML", "CSS", "Javascript"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/selnet.png",
  },
  {
    id: "10",
    title: "Portfolio Website",
    websitelink: "https://javid-hussain.netlify.app/",
    languages: ["React", "SASS/SCSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/javid.png",
  },
  {
    id: "11",
    title: "Studio Ghibli",
    websitelink: "https://studio-ghibli-go.netlify.app/",
    languages: ["React", "SASS/SCSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/ghibli.png",
  },

  {
    id: "12",
    title: "Freud",
    websitelink: "https://sigmundfreud.netlify.app/",
    languages: ["React", "SCSS", "HTML", "GSAP"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "/assets/images/freud.png",
  },
  {
    id: "13",
    title: "Stremio",
    websitelink: "eazypizz.netlify.app",
    languages: ["React", "SASS/SCSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "",
  },

  {
    id: "14",
    title: "Youtube App",
    websitelink: "https://youtube-go.netlify.app/g",
    languages: ["React", "SASS/SCSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "",
  },
  {
    id: "15",
    title: "Currency Converter",
    websitelink: "https://youtube-go.netlify.app/g",
    languages: ["React", "SASS/SCSS", "HTML"],
    desc: "Portfolio Project for myself, as a front end developer, I tried to make my portfolio look more creative as well as interactive",
    goal: "",
    challanges: "",
    solution: "",
    screenshots: "",
  },
];
export default projects;
